### PR TITLE
Fixed issue related to compare unnormalized versions

### PR DESCRIPTION
**Pull request by llaville**
Apply fix suggested on https://github.com/justinrainbow/json-schema/issues/708 for issue #30

### CODE REVIEW

**Comment by SmetDenis** [comment]
Hello, @llaville 

Thank you so much for your pull requests.
I really appreciate it.


Let me check it these days, and I'll share my feedback soon.

PS. Sorry, I just don't have the actual ability to do that right now. But I'll definitely try to do it this weekend.

**Comment by SmetDenis** [comment]
Btw, did you test it via `make test` and `make codestyle`, or you can do it with Github Actions.

**Comment by llaville** [comment]
> Btw, did you test it via `make test` and `make codestyle`, or you can do it with Github Actions.

Here are results 

<details>
<summary>`make test` results</summary>

```text
make[1]: Entering directory '/shared/backups/forks/Composer-Diff'
make[1]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[1]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPUnit - Run all tests
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.

Random Seed:   1705384051

........................S....S...S..S....S.S...S.S............... 65 / 82 ( 79%)
.........SSSSSSSS                                                 82 / 82 (100%)

Time: 00:04.594, Memory: 22.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 82, Assertions: 221, Skipped: 16.

Generating code coverage report in PHP format ... done [00:00.001]

Generating code coverage report in Clover XML format ... done [00:00.010]


Code Coverage Report:
  2024-01-16 05:47:36

 Summary:
  Classes: 50.00% (5/10)
  Methods: 72.97% (27/37)
  Lines:   94.35% (317/336)

JBZoo\ComposerDiff\Commands\DiffAction
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% ( 64/ 64)
JBZoo\ComposerDiff\Comparator
  Methods:  50.00% ( 2/ 4)   Lines:  92.50% ( 37/ 40)
JBZoo\ComposerDiff\ComposerLock
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% (  9/  9)
JBZoo\ComposerDiff\Diff
  Methods:  57.14% ( 4/ 7)   Lines:  80.36% ( 45/ 56)
JBZoo\ComposerDiff\Exception
  Methods:  ( 0/ 0)   Lines:  (  0/  0)
JBZoo\ComposerDiff\Package
  Methods:  60.00% ( 3/ 5)   Lines:  89.47% ( 17/ 19)
JBZoo\ComposerDiff\Renders\AbstractRender
  Methods:  85.71% ( 6/ 7)   Lines:  96.67% ( 29/ 30)
JBZoo\ComposerDiff\Renders\Console
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% ( 28/ 28)
JBZoo\ComposerDiff\Renders\JsonOutput
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% (  5/  5)
JBZoo\ComposerDiff\Renders\Markdown
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 38/ 38)
JBZoo\ComposerDiff\Url
  Methods:  50.00% ( 2/ 4)   Lines:  95.74% ( 45/ 47)
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[1]: Leaving directory '/shared/backups/forks/Composer-Diff'
```

</details>


<details>
<summary>`make codestyle` results</summary>

```text
make[1]: Entering directory '/shared/backups/forks/Composer-Diff'
make[1]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[1]: Entering directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  Check Coding Standards with PhpCsFixer
make[3]: Entering directory '/shared/backups/forks/Composer-Diff'
Config: /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/PhpCsFixer/php-cs-fixer.php
PHP CS Fixer 3.46.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.14
Loaded config JBZooStyle from "/shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/PhpCsFixer/php-cs-fixer.php".
Using cache file "/shared/backups/forks/Composer-Diff/build/php-cs-fixer-cache.json".


make[3]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPcs - Checking PHP Code Sniffer
Config: /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/phpcs.xml
........... 11 / 11 (100%)


Time: 289ms; Memory: 12MB

make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPmd - Mess Detector Checker
Config: /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/phpmd.xml
PHPMD 2.15.0

Found 0 violations and 0 errors in 162ms

No mess detected
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPmnd - Magic Number Detector
phpmnd version 3.3.0 by Povilas Susinskas

 11/11 [============================] 100%

------------------------------------------------------------------------------------------------------------------------

Total of Magic Numbers: 0
Time: 00:00.128, Memory: 14.00 MB
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPcpd - Find obvious Copy&Paste
phpcpd 6.0.3 by Sebastian Bergmann.

No clones found.

Time: 00:00.004, Memory: 4.00 MB
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  PHPStan - Static Analysis Tool
Config: /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/phpstan.neon
 11/11 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%



 [OK] No errors


make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  Psalm - static analysis tool for PHP
Config:   /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/psalm.xml
Baseline: /shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/psalm-baseline.xml
Psalm 5.19.0@06b71be009a6bd6d81b9811855d6629b9fe90e1b
Warning: "findUnusedBaselineEntry" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedBaselineEntry" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.1 (inferred from composer.json).
Scanning files...
Analyzing files...

░░░░░░░░░░░
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  Phan - super strict static analyzer for PHP
Config: /shared/backups/forks/Composer-Diff/.phan.php
Phan 5.4.3
php-ast version 1.1.1
PHP version used to run Phan: 8.2.14
Memory usage after analysis completed: 91MB/91MB
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[2]: Entering directory '/shared/backups/forks/Composer-Diff'

>>>> >>>> >>>> >>>> >>>> >>>>  Composer - Checking common issue
Checking composer.json: WARNING
require.symfony/console : unbound version constraints (>=5.4) should be avoided
require.symfony/process : unbound version constraints (>=5.4) should be avoided
require.composer/semver : unbound version constraints (>=1.0) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.39.2
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.6.6
PHP version: 8.2.14
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 3.0.11 19 Sep 2023
cURL version: 7.88.1 libz 1.2.13 ssl OpenSSL/3.0.11
zip: extension present, unzip present, 7-Zip not available
make[2]: [/shared/backups/forks/Composer-Diff/vendor/jbzoo/codestyle/src/Makefiles/03_tests.Makefile:116: test-composer] Error 1 (ignored)

>>>> >>>> >>>> >>>> >>>> >>>>  Composer - Validate system requirements
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- require.symfony/console : unbound version constraints (>=5.4) should be avoided
- require.symfony/process : unbound version constraints (>=5.4) should be avoided
- require.composer/semver : unbound version constraints (>=1.0) should be avoided
Checking platform requirements for packages in the vendor dir
composer-runtime-api 2.2.2      success
ext-ctype            *          success provided by symfony/polyfill-ctype
ext-dom              20031129   success
ext-filter           8.2.14     success
ext-gd               8.2.14     success
ext-json             8.2.14     success
ext-libxml           8.2.14     success
ext-mbstring         *          success provided by symfony/polyfill-mbstring
ext-openssl          8.2.14     success
ext-pcre             8.2.14     success
ext-phar             8.2.14     success
ext-posix            8.2.14     success
ext-reflection       8.2.14     success
ext-simplexml        8.2.14     success
ext-spl              8.2.14     success
ext-tokenizer        8.2.14     success
ext-xml              8.2.14     success
ext-xmlwriter        8.2.14     success
php                  8.2.14     success

>>>> >>>> >>>> >>>> >>>> >>>>  Composer - List of outdated packages
Color legend:
- patch or minor release available - update recommended
- major release available - update possible
roave/security-advisories dev-master c892bcc dev-master d38bb90 Prevents installation of composer packages with know...
symfony/console           v6.4.2             v7.0.2             Eases the creation of beautiful and testable command...
symfony/process           v6.4.2             v7.0.2             Executes commands in sub-processes
make[2]: Leaving directory '/shared/backups/forks/Composer-Diff'
make[1]: Leaving directory '/shared/backups/forks/Composer-Diff'
```

</details>

**Comment by SmetDenis** [comment]
Awesome. Thank you!

**Pull request merged**
